INSERT INTO BOOK_VALUE(id,BOOK_ID, BOOK_NAME, AUTHOR, AVAILABLE_COPIES, TOTAL_COPIES) 
values (1001, 'B1212', 'History of Amazon Valley', 'Ross Suarez', 0, 2);

INSERT INTO BOOK_VALUE(id,BOOK_ID, BOOK_NAME, AUTHOR, AVAILABLE_COPIES, TOTAL_COPIES) 
values (1002, 'B4232', 'Language Fundamentals', 'H S Parkmay', 5, 5);